"""Light text normalisation shared by the parser and boundary detection.

This is deliberately narrow. Full pre-processing is step 3 of the workflow;
here we only do the normalisation the parser itself needs so that boundary
matching is not defeated by a non-breaking space or a smart quote.
"""

from __future__ import annotations

import re

#: Characters Word inserts that behave as spaces but break naive regexes.
_SPACE_LIKE = {
    " ": " ",  # non-breaking space
    " ": " ",  # figure space
    " ": " ",  # narrow no-break space
    "​": "",   # zero-width space
    "﻿": "",   # zero-width no-break space
    "‑": "-",  # non-breaking hyphen
}

_WHITESPACE = re.compile(r"[ \t\r\f\v]+")

#: A marker typed into the text rather than generated by Word's numbering:
#: "1.", "2)", "(3)", "a.", "iv)", "-", "•".
LITERAL_MARKER = re.compile(
    r"""^\s*
    (?P<marker>
        \(\s*(?:\d{1,3}|[A-Za-z])\s*\)
      | (?:\d{1,3}|[A-Za-z]|[ivxlcdmIVXLCDM]{1,6})\s*[.)\]]
      | [-–—•▪○●·∙o]
    )
    \s+
    """,
    re.VERBOSE,
)


def clean_text(text: str) -> str:
    """Replace exotic whitespace with plain spaces, without trimming content."""
    for source, target in _SPACE_LIKE.items():
        text = text.replace(source, target)
    return text


def collapse_whitespace(text: str) -> str:
    """Normalise runs of spaces and strip the ends."""
    return _WHITESPACE.sub(" ", clean_text(text)).strip()


def detect_literal_marker(text: str) -> str | None:
    """Return a list marker typed at the start of ``text``, if any."""
    match = LITERAL_MARKER.match(clean_text(text))
    return match.group("marker").strip() if match else None


#: Length-preserving substitutions, safe to use when regex offsets must map
#: back onto the original run text.
_SPACE_LIKE_1TO1 = {source: target for source, target in _SPACE_LIKE.items() if len(target) == 1}


def normalize_for_matching(text: str) -> str:
    """Normalise whitespace without changing string length.

    Boundary detection matches against this and then uses the match offsets to
    trim the original runs, so any substitution here must be one character for
    one character.
    """
    for source, target in _SPACE_LIKE_1TO1.items():
        text = text.replace(source, target)
    return text


def literal_marker_span(text: str) -> tuple[str, int] | None:
    """Return ``(marker, end_offset)`` for a marker typed at the start of ``text``.

    The offset is into the original string, so it can be used to trim runs
    without disturbing their formatting.
    """
    match = LITERAL_MARKER.match(normalize_for_matching(text))
    return (match.group("marker").strip(), match.end()) if match else None
